### ISSUE TITLE
Research if is possible to migrate all the Metadata validation using AJV

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#105]
https://github.com/epoberezkin/ajv
https://github.com/json-schema/json-schema/wiki/v5-Proposals

**Comment by danigomez** [comment]
It seems that the JSON Schema spec support recursive definitions using JSON Pointers ($ref to the definition file who has a property that points to itself), the thing that's left to solve is how to handle the functions that could be passed to any field prop and evaluated in the expression helper.

**Comment by JonatanSalas** [comment]
Great, only rest to know how to manage the functions

**Comment by JonatanSalas** [comment]
Not needed! In newer version of redux-autoform you'll have a declarative way to write forms, and also, we'll keep old schema support.
