### ISSUE TITLE
Update to react-redux v5

### ISSUE THREAD

**Issue by vedrani** [redux-autoform/redux-autoform#118]
Update package.json to support not only react-redux V4 but also V5. V5 is back-compatible to V4 but have improvements in performance.

https://github.com/reactjs/react-redux/releases/tag/v5.0.0

**Comment by JonatanSalas** [comment]
There's a PR from greenkeeper now #116. I will merge it now, test a little bit, and afternoon I will release a newer version! 

Thanks!

**Comment by vedrani** [comment]
Hi, 

When you plan to publish new version with react-redux v5?
You should also update dependency on redux-form V5 to 5.3.4.
This should be straightforward because react-redux v5 is back-compatible.
If I can help, please tell. Thanks :)

https://github.com/erikras/redux-form/releases/tag/v5.3.4

**Comment by JonatanSalas** [comment]
@vedrani this is currently updated! I have added react-redux v5, and also redux-form v5.3.4! The latest release v0.12.0-experimental updates both dependencies!
