### ISSUE TITLE
Match dateTimePicker.less case

### ISSUE THREAD

**Issue by suchostone** [redux-autoform/redux-autoform#20]
styles-defaultfactories.less content is as below, but lib/less/defaultFactories includes DateTimePicker.less with capital D.

// third party
@import './defaultFactories/Lookup';
@import './defaultFactories/dateTimePicker';
@import './defaultFactories/Checkbox';

Seems to be already fixed at source-code but npm install redux-autoform brings old version.

**Comment by andrerpena** [comment]
Oh. Sorry for that. I'll republish the NPM.

**Comment by andrerpena** [comment]
I made a new NPM publish, hope this fixes the issue
