### ISSUE TITLE
Material UI support

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#21]
Hi, first of all, thanks for your project! I'm currently working with it, and it's a cool stuff.

I have been looking a little bit at your code, and some parts could be upgraded to ES6 sintax.. I would like to make a PR with this, and even more, I want to create a MaterialUIComponentFactory, for those who use material-ui in their projects. 

Let me know what do you think about this.

**Comment by andrerpena** [comment]
That's amazing. Feel free to create your PR. If you'd like a Skype call, let me know.

**Comment by andrerpena** [comment]
Also, if you happen to become a frequent contributor, I'll invite you to the organization.

**Comment by JonatanSalas** [comment]
Great, I will be working on that, maybe in the weekend I will submit a PR with the changes :+1: 
If I have some trouble, I will ask you in this issue!

**Comment by andrerpena** [comment]
Deal. Thank you very much.

**Comment by JonatanSalas** [comment]
@andrerpena I have made a PR for the es6 refactor #23! Hope you can check it as soon as you can!

**Comment by andrerpena** [comment]
I'll do this first thing in the morning. Thank you very much for this

Em 16 de jul de 2016 19:31, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
You are welcome! Glad to help your project grow!

**Comment by andrerpena** [comment]
Let me know if you want write access

**Comment by JonatanSalas** [comment]
If you want to give me write access I don't have any trouble!

I will keep working through PRs, so you can check the codebase I make and confirm if it works or needs thinks to solve, in order to not break the master branch!

**Comment by andrerpena** [comment]
You have been invited @JonatanSalas

**Comment by JonatanSalas** [comment]
Thanks! @andrerpena! For now I will start to work in material-ui integration.

**Comment by JonatanSalas** [comment]
@andrerpena I been started to think that Autoform component could have a new property like uiType, that will be String. You could specify which type of UI you like Autoform get, for example "material-ui", "bootstrap" and internally match this type to a generic factory which determines what kind of ui-factory should use.  

This type could be an option, not required, you could use this, or provide your own componentFactory to autoform. 

What do you think?

**Comment by andrerpena** [comment]
Are you suggesting that there would be 2 ways to choosing the factory.. one by explicitly passing it in, and the other by passing this prop that would allow Autoform to automatically pick a factory?

**Comment by JonatanSalas** [comment]
Exactly, it's more easy if you want to use a built-in factory, avoiding you as a lib user to import the defaultEditComponentFactory, and passing it as props, and you keep maintaining the ability to pass a custom factory if you don't want to use the built-in's redux-autoform provide.

**Comment by andrerpena** [comment]
How are we dealing with the demo? I kind of prefer that the Bootstrap and the Meterial demo to be completely separate, because the presets won't be the same. I mean, we can still leverage the editor and the layout and everything but making them apart.

Do you prefer it that way or do you think adding another "switch" in the demo is a good idea?

**Comment by JonatanSalas** [comment]
Well, if you want we can make another demo for Material-ui, that's not a big trouble :) 
First of all I will do the material-ui integration, and test that all it's working fine and well abstracted, and then after PR approbed I will make the demo work!

**Comment by andrerpena** [comment]
@JonatanSalas But how are you testing without the Demo? I mean.. I created the Demo not for the people to see, but so I can debug it faster hauhauh.. just kidding.

**Comment by andrerpena** [comment]
@JonatanSalas It's just my 2 cents but I kind of feel like we should start the Material with a demo.

**Comment by JonatanSalas** [comment]
As an Isolated enviroment to test my components I use carte-blanche project. Do you know it? https://github.com/carteb/carte-blanche

**Comment by andrerpena** [comment]
I'll take a look at it, thank you!

**Comment by JonatanSalas** [comment]
Jaja you are welcome! :)

**Comment by JonatanSalas** [comment]
@andrerpena I have notice that in your code you have two types of factory. An Edit factory and a DetailsFactory, could you explain me a little bit about this? :)

**Comment by andrerpena** [comment]
@JonatanSalas , I'm thinking about renaming the components folder and the factories to indicate they are **bootstrap**, like this:

![bootstrap](http://i.imgur.com/khxqKlT.png)

See that there's no DefaultComponentFactory anymore. Now it's BootstrapEditComponentFactory.

What do you think? Can I do it and commit it?

**Comment by andrerpena** [comment]
A details component factory is meant to be used for a details scenario (not for editing).
Actually.. I was envisioning 3 types of forms:
- Edit
- Details
- Search (similar to Edit, but this one supports grouping and operators like greater than).

If you have a better idea, please let me know.

**Comment by JonatanSalas** [comment]
@andrerpena Well, I think it's good, but we could use a more modular approach like this: 
- **components**
  - _bootstrap_
  - _material-ui_
- **factory**
  - _bootstrap_
  - _material-ui_
  - **ComponentFactory.js**
- **less** 
  - _bootstrap_
  - _material-ui_
- **lib** -> _(this could be named as metadata or metadata-validator or something like this)_
- **AutoForm.js**
- **AutoFormInternal.js**
- **index.js**

What do you think?

**Comment by JonatanSalas** [comment]
@andrerpena thanks for the explanation about component factory types :)

**Comment by andrerpena** [comment]
Ok, I agree with your directory structure proposal, are you doing this or do you want me to do it? I can only do this tonight.
Thank you.

**Comment by JonatanSalas** [comment]
@andrerpena in the feature branch I'm developing I have organized the directory structure like this, so when I submit a PR with the changes you will see this structure. 

Do you agree about a rename over lib folder? In this case, what name would you propose?

**Comment by andrerpena** [comment]
@JonatanSalas 

metadata is what most of this folder does, but it also deals with localization and it has some helpers like arrayHelper (which we can think of removing). I agree of renaming this folder to metadata as long as we take localization out. You can rename it now and we organize it better later.. or you can give your shot on the organization and I let you know of something I would change.

**Comment by JonatanSalas** [comment]
Okey, I'm currently organizing it and I agree to renaming lib as metadata and extract localization! :)

**Comment by JonatanSalas** [comment]
@andrerpena another question about **edit, details and search** component factory. It would be better if you have only one Factory per UI, and to get the edit/details/search one you pass a flag to it. 

Do you agree?

**Comment by andrerpena** [comment]
I agree. The reason why I didn't do it that way from the beginning was that
I wasn't really thinking in supporting multiple UI frameworks. I was more
interested in supporting multiple components. Go ahead. I agree to you.

Em 18 de jul de 2016 5:35 PM, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
@andrerpena  I started to think that If we designed it a little bit we could extract the ui component factories into small units like: 
- redux-autoform-material-ui
- redux-autoform-bootstrap
- redux-autoform-other-ui

And redux-autoform working as core library, making ui pluggeable. what do you think?

**Comment by andrerpena** [comment]
Yes, that makes sense, as long as `redux-autoform` keeps being the main project, but I think that's how you're thinking too.

The advantage of this approach is that you, as a user, don't have to download a bunch of code/styles that you're not using, and that makes `redux-autoform` agostic of the UI framework.

Do you care making the refactoring? Do you need help? How do you think we should do it? What about the demo? The demos should probably be in the UI libraries but with LINKs in the main project `readme.md`.

Also, I can invite you to the organization. We can even rename it or create an organization specifically for Redux-Autoform. I'm not sure about that.

**Comment by JonatanSalas** [comment]
And even too, we part the trouble in two, we separate the metadata management from ui, so we can focus on improvements on differents projects. 

We can make a guideline too for those who want to create a ui library extension. 

Well, actually I will submit you a PR with the library restructuration. 

Then I will add material ui support in this library, and when we can abstract how to organize a ui project for material, bootstrap, etc, and then we start the migration. 

Do you agree? :)

About the organization, do with that what you want! If you think that an organization for redux-autoform maybe a good decision just do it! I will keep on helping to improve this project :D

**Comment by andrerpena** [comment]
Thank you very much @JonatanSalas , yes.. submit Material-UI as is and then we figure out how to split the projects apart.

**Comment by JonatanSalas** [comment]
@andrerpena What are you going to do with redux-autoform, are you going to create an organization for it?

Tomorrow I will keep working with material-ui integration!

**Comment by andrerpena** [comment]
@JonatanSalas, yes I will create an organization and invite you. How would you name it? Redux-Autoform?

**Comment by andrerpena** [comment]
or something more creative...

**Comment by JonatanSalas** [comment]
@andrerpena for now I think that Redux-Autoform is a good name, but we can make an issue to discuss about it. It would be good too if we can make a good logo for the organization :)

**Comment by andrerpena** [comment]
@JonatanSalas sounds good. Expect an invitation shortly.

**Comment by JonatanSalas** [comment]
@andrerpena okas! Thank you :+1:

**Comment by justingreenberg** [comment]
i know i'm a little late to the game here, but since there is a hard dependency on redux-form, i would suggest a name that includes it, ie. redux-form-auto or redux-form-builder

**Comment by JonatanSalas** [comment]
@andrerpena I will close this, since I'm working on a different git repo! :+1:
