### ISSUE TITLE
Reopen Match dateTimePicker.less case

### ISSUE THREAD

**Issue by suchostone** [redux-autoform/redux-autoform#22]
Hi! I have created this issue as #20 was already closed but after installing 0.6.2 version, lib/less/defaultFactories still includes DateTimePicker.less with capital D.

previous issue: https://github.com/gearz-lab/redux-autoform/issues/20

Thanks

**Comment by andrerpena** [comment]
Sorry. This commit should have fixed it: https://github.com/gearz-lab/redux-autoform/commit/6d371df784d2b216cfafe0f0eabc57537a5e0a9d

**Comment by suchostone** [comment]
Thanks!
