### ISSUE TITLE
Carte Blanche is not working

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#28]
@JonatanSalas , I'm trying to follow your suggestion of using Carte Blanche but when I set up it exactly like the docs say, it gives me this error:

![image](http://i.imgur.com/1nxe08A.png)

Steps to reproduce:
- Update the master branch to the latest version
- Uncomment these lines: https://github.com/gearz-lab/redux-autoform/commit/f67737859e6ac39dc51decd177abfd1a6852dcec#diff-d6a36c83884182f30dadbc9d034d39d6R40
- `npm start`

Do you know what would be the problem, thank you!

**Comment by JonatanSalas** [comment]
@andrerpena I will take a look later and try to solve it! :)

**Comment by andrerpena** [comment]
@JonatanSalas thank you. I'll do the same.

**Comment by andrerpena** [comment]
Here are the errors:

> ERROR in C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/",
> "componentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placehol
> der.js
> Module not found: Error: Cannot resolve module 'c:Gitsrccomponents' in C:\Git\redux-autoform\node_modules\carte-blanche\dist\src\assets
>  @ C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/","compo
> nentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placeholder.js
>  6:26-145
> 
> ERROR in C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/",
> "componentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placehol
> der.js
> Module not found: Error: Cannot resolve module 'c:Gitsrccomponents' in C:\Git\redux-autoform\node_modules\carte-blanche\dist\src\assets
>  @ C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/","compo
> nentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placeholder.js
>  6:153-417
> 
> ERROR in C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/",
> "componentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placehol
> der.js
> Module not found: Error: Cannot resolve module 'c:Gitsrccomponents' in C:\Git\redux-autoform\node_modules\carte-blanche\dist\src\assets
>  @ C:/Git/redux-autoform/~/carte-blanche/dist/src/dynamic-resolve.js?{"filter":"/(///[A-Z][a-zA-Z]_.?///index|///[A-Z][a-zA-Z]_)//.(jsx?|es6|react//.jsx?)$/","compo
> nentRoot":"../src/components","context":"c://Git//redux-autoform","basePath":"//carte-blanche"}!C:/Git/redux-autoform/~/carte-blanche/dist/src/assets/placeholder.js
>  6:429-633

**Comment by andrerpena** [comment]
This error is because Windows is currently unsupported, which is my OS, so I'm closing this for now, and reverting the commit.
