### ISSUE TITLE
Create a decent logo (this one is a stub)

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#30]

**Comment by JonatanSalas** [comment]
This is almost done, I need to make it as svg to get better resolution fidelity. https://avatars3.githubusercontent.com/u/20527600?v=3&s=200

**Comment by andrerpena** [comment]
I like it =)

Em 23 de jul de 2016 10:17 PM, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
@andrerpena now it looks better, I have changed to get better resolution fidelity :)
https://avatars3.githubusercontent.com/u/20527600?v=3&s=200

**Comment by andrerpena** [comment]
Very good. Looks great on my profile. Thanks for that.
PS: Why do you hide it on your profile?

**Comment by JonatanSalas** [comment]
On my github profile doesn't appear? :open_mouth:

**Comment by JonatanSalas** [comment]
Seems that by default github hides your membership to an organization and then you can choose to make it public, now you should be able to see it in my profile! :smile:

**Comment by andrerpena** [comment]
Great!
