### ISSUE TITLE
Remove the formato reference

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#31]
I created the 'formato' project because I didn't know about Numbro. This is now deprecated.

**Comment by JonatanSalas** [comment]
@andrerpena where is located the formato reference? This is solved?

**Comment by andrerpena** [comment]
Formato was being used for number/currency conversion. I did this because I didn't know Numbro existed. Fortmato is in the `gearz-lab` org. Keep me assigned on this. As soon I can take a look at it I'll remove it.

**Comment by JonatanSalas** [comment]
Cool! Keep this issue as is :)

**Comment by JonatanSalas** [comment]
@andrerpena I have been looking at redux-autoform and seems that formato it's not in the core. Maybe you have advanced on it. So I will close this issue. If I make a mistake, please re open it!
