### ISSUE TITLE
Radio Button on Demo

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#33]
When performing the code base refactor, I notice that we have a Radio component but it's not present on the demo. 

Radio has an issue to solve? Or you forget to add it?

**Comment by andrerpena** [comment]
I just didn't time to create the demo. I think it's working just fine. I can put it on the demo today =)

**Comment by JonatanSalas** [comment]
okay! Thanks :)

**Comment by JonatanSalas** [comment]
Can you change the name of the org from "redux-autoform" to "Redux Autoform"?

**Comment by andrerpena** [comment]
About the renaming... Just did it.

**Comment by andrerpena** [comment]
Rejoice http://redux-autoform.github.io/redux-autoform/demo.html?preset=componentsRadio
