### ISSUE TITLE
Support for files upload

### ISSUE THREAD

**Issue by suchostone** [redux-autoform/redux-autoform#34]
Hi! Just wondering if you are planning to add any support for files upload.

Btw, the library is great.

Thanks in advace.

**Comment by andrerpena** [comment]
That's a good suggestion @suchostone . Fortunately Redux-Form does have support so it's just a matter of creating the component and demos. I'm looking into it next weekend. Ok?

**Comment by suchostone** [comment]
Sounds Excellent. Thanks!

**Comment by andrerpena** [comment]
Working on this...

**Comment by JonatanSalas** [comment]
@andrerpena what about this? Do you have any advance, let me know if you have done something. If not I will take this issue to make it work for bootstrap-ui redux-autoform/redux-autoform-bootstrap-ui#2 :smile:

**Comment by JonatanSalas** [comment]
I will close this issue since it comes related to bootstrap-ui, @andrerpena when you could please confirm to me if you have been putting an eye on this! :smile:

**Comment by andrerpena** [comment]
I'm assigned to do it.. I just didn't it yet because I was dealing with the demo migration.

**Comment by andrerpena** [comment]
@suchostone - This is the new issue so you can keep track: https://github.com/redux-autoform/redux-autoform-bootstrap-ui/issues/2

**Comment by suchostone** [comment]
Thanks @andrerpena!
