### ISSUE TITLE
Support for an alternative and simpler syntax for schema

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#35]
redux-autoform's schema syntax is somewhat complex. There's need for this complexity but may be it should support a simpler alternative syntax that abstracts the concept of `entities` and `layouts`. 

For instance, this would be enough for running a simple form:

```
[
    { name: 'name', type: 'string' },
    { name: 'dateOfBirth', type: 'date' },
] 
```

This would also work:

```
{
    name: {
        type: 'string'
    },
    dateOfBirth: {
        type: 'string'
    }
}
```

The only problem with the above approach is that I favored `arrays` over `objects` and I did that because arrays are easier to merge. I mean, adding a field in the position 3 and removing the one on position 1 is kind of easier using arrays. But I'm open to alternatives anyway.

What do you guys think?
@JonatanSalas ?

**Comment by JonatanSalas** [comment]
We could simplify the usage of the lib as you said, letting the user create the schema in a more simpler approach, but in the code adapt this json to treat it as an array. 
This will add a minor complexity to us as lib developers, but it's not a big trouble.

@andrerpena what do you think?

**Comment by andrerpena** [comment]
@JonatanSalas Yes that's exactly the way I was thinking. The advantage of supporting a simpler syntax is that we can attract developers that don't need all those fancy features.

I'll refine the ideia and then I'll post a proposal here.

**Comment by JonatanSalas** [comment]
@andrerpena that's good! I agree that with this we can attract more people. This project is a big goal!

**Comment by andrerpena** [comment]
I'm going to add multiple micro non-breaking changes until this functionality is complete

**Comment by andrerpena** [comment]
Objects are now supported instead of arrays for **everything**, example: https://github.com/redux-autoform/redux-autoform/blob/master/demo/presets/ComponentsCheckbox.txt

... but we can't close this because I still have to implement support for this: 

```
{
    name: {
        type: 'string'
    },
    dateOfBirth: {
        type: 'string'
    }
}
```

**Comment by andrerpena** [comment]
When there's only 1 entity, now you DONT have to specify the entity name. The same is valid for layouts. This is important for the simple syntax I'm trying to achieve.

**Comment by andrerpena** [comment]
Simple schema is now supported, tested and checked in. But I'm only closing this tomorrow because I have to republish the demo and I'm really tired right now.

Example: https://github.com/redux-autoform/redux-autoform/blob/master/demo/presets/schemaTypesSimple.txt

**Comment by andrerpena** [comment]
Documentation: https://github.com/redux-autoform/redux-autoform/blob/master/docs-md/documentation.md#schema-format

Demo: http://redux-autoform.github.io/redux-autoform/demo.html?preset=schemaTypeSimple

**Comment by JonatanSalas** [comment]
Great work!!
