### ISSUE TITLE
Redux-Autoform features proposal 

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#38]
I want to create this issue to be used as a thread for discussions about features or improvements over the redux-autoform API. 

About a lot of exchanges we got the following list: 

TODO: 
- [ ]  Create a homepage 
- [ ] Migrate redux-form from v5.X to v6.X when released and full tested. 

DONE:
- [x] Make the library as a core and UI agnostic. 
- [x] Make small git repositories for differents UI types components and expose an index.js api. 
- [x] Make a git project as boilerplate for those collaborators who want to add it's own ui types. 
- [X] Update the documentation and make one demo per ui git project.
- [x] Re define the way to declare the schema to make it more easier to read, and make a util class to treat as an array. 
- [X] Add support for Wizard Style form. 
- [x] Define how styles per ui type project should be managed. Modular CSS? Inline styles with the help of radium lib? 
- [x] Add support for file-upload components.
- [x] Fix codecov and coveralls to view % of test coverage 
- [x] Fix travis-ci and greenkeeper

Well, if I forget something else please add it! :)

**Comment by andrerpena** [comment]
That's a good compilation.

The UI project should be a "factory" (not necessarily called that way) that should be able to provide components given a "mode" and a "type" (this is based on your own idea). We can support 3 modes that I can think of right now: "edit", "details" and "search". 

We can even get more flexible, I mean... What if the factory gets a "mode" and a "propertyMetadata"? This way... the factory can provide a TextBox if the type is "string" and the length is smaller than 30 characters and a TextArea otherwise. This is maximum flexibility for the factory.

**Comment by JonatanSalas** [comment]
@andrerpena I'm completely agree about the UI project as factory, and think about how to make it as flexible as possible. 

We need to discuss about how to make the Styles from the UI projects as flexibles as possible too.

**Comment by andrerpena** [comment]
Just created the under-development label. Please assign yourself to the task and add this label so I won't touch it. Does that make sense? Now you can see what's being done just by looking at: https://github.com/redux-autoform/redux-autoform/issues

**Comment by JonatanSalas** [comment]
@andrerpena cool! I will use it, so we can now what we have assigned!

**Comment by JonatanSalas** [comment]
@andrerpena I have created three repositories, with @danigomez, we will try to solve out how to extract the UI to different projects. 

The projects are the following ones: 
- One for material-ui
- One for bootstrap-ui
- One for boilerplate, it will work as starter kit for other UIs extensions

We are going to work on those git repositories, and then we are going to solve out how to integrate them with redux-autoform itfself! :)

**Comment by andrerpena** [comment]
Amazing job. Let me know if you need any help.

**Comment by JonatanSalas** [comment]
Bootstrap-ui seems to be easy to extract because it's already done, so we will start with this, and then we will go for material-ui! 

If I need some help I will let you know!

**Comment by andrerpena** [comment]
You are extracting the Bootstrap UI **as is** right? After that I can help making the enhanced factory that supports "mode", ok?

**Comment by JonatanSalas** [comment]
Yes, I'm extracting as is! Good, thanks! :)

**Comment by JonatanSalas** [comment]
@andrerpena could you guide me a little bit on how to publish a git repository into npm? :)

**Comment by JonatanSalas** [comment]
@andrerpena we are going to do something like this in redux-autoform to integrate the other ui libs:

``` java
class UIManager {
  allowedUIs = [
    'bootstrap',
    'material-ui'
  ];

  factoryTypes = {};

  constructor() {
    const { allowedUIs, factoryTypes } = this;

    allowedUIs.forEach((value) => {
      factoryTypes[value] = require(`redux-autoform-${value}-ui`);
    });
  }

  getFactory(type) {
    return this.factoryTypes[type];
  }
}
```

what do you think?

Other thing I want to ask you is that if we can create a branch directly in this project and work on it. We can define a milestone and then create a branch for this milestone and keep working till this version it's complete.

**Comment by andrerpena** [comment]
In order to publish an NPM:
- Log into npmjs.com and create a user
- Make sure you have a proper packages.json for your project, other wise type `npm init`
- Type `npm adduser` or `npm add user` to login 
- Type `npm publish`.

It's quite simple

**Comment by andrerpena** [comment]
@JonatanSalas , sorry, I was thinking differently.

I don't think you need an UI manager, you just need import whatever factory you want and use it.

Example:

``` js
import materialFactory from 'material-factory'; //this came from the separate repository
...
render() {
    return <Autoform factory={materialFactory} />;
}
```

I mean.. `AutoForm` is now 100% agnostic of your factory.

After you do it, I'll work on **improving** the factory so it will support "mode" and add flexibility.

Does that make sense?

**Comment by JonatanSalas** [comment]
@andrerpena, I'm thinking the code in the way that a lib user only type something like: 

``` javascript
class App {
  render() {
      return <Autoform type="material-ui"/>;
  }
}
```

In this way, you abstract the developer that use the library from the concept of factory, and you let autoform to manage internally the factory creation. 

In this way we add a bit more of responsability to redux-autoform, but since the ui is agnostic from the core that's not a big trouble, and with this we gain a more clearer API.

**Comment by andrerpena** [comment]
Can we agree on an intermidiate solution?

**We give the user 2 options**:

If you do this:

``` javascript
class App {
  render() {
      return <Autoform ui="material-ui"/>;
  }
}
```

... than you can operate your magic and dynamically import the factory. **But there's still the case in which the user is importing a homebrew factory that is not an NPM module**, because of that, we should probably be able to import manually, using the same variable.

``` javascript
class App {
  render() {
      return <Autoform ui={someUiThatImImportingManually}/>;
  }
}
```

So it doesn't really matter whether you are passing a plugin or a string. It will just work.

**Comment by JonatanSalas** [comment]
Totally agreed on the intermediate proposal! :) Let's go for this approach!

**Comment by JonatanSalas** [comment]
@andrerpena what about the work in branches from this project? Do you think it's good? Or you want us to fork and submit PRs? Let me know it! :)

**Comment by andrerpena** [comment]
I don't really care if you submit PRs or directly commit to master as long as we're aligned on what and how you're doing stuff. As for branches.. I only use feature-branches for medium-to-complex features. Otherwise I just commit to master :)

**Comment by JonatanSalas** [comment]
@andrerpena we have a trouble with  @danigomez trying to publish a npm package, could you help us? 

He got this error: 

```
     C:\Proyectos\OpenSource\ReduxAutoFormBootstrap\node_modules\redux-autoform-utils\src\index.js:2
     export * from './localization/dateLocalizer'
     ^^^^^^
     SyntaxError: Unexpected token export
```

We are using es6 syntax, previously to publish the code on npm, we should transpile it to es5?

**Comment by andrerpena** [comment]
@JonatanSalas  Oh yes defnititely...

RAF has a command called `build-lib`. You always have to call `build-lib` **before** publishing. You also have to make sure that you didn't publish the current version already. I mean, every time you publish, you got to go to the packages.json file and change the version.

**Comment by andrerpena** [comment]
@JonatanSalas , the `build-lib` NPM command on RAF relys on a Node script that I've implemented. You should look into it from RAF and copy and paste inside each of the UI projects you are creating

**Comment by JonatanSalas** [comment]
@andrerpena thank you so much! :smile:

**Comment by andrerpena** [comment]
@JonatanSalas , also, don't forget the `.npmignore` file, because the `src` folder shouldn't be publish, but the `lib` folder which is generated by the `build-lib` script.

**Comment by JonatanSalas** [comment]
@andrerpena I will start to migrate all the issues from ui to the ui libs git repositories, do you agree?

**Comment by andrerpena** [comment]
@JonatanSalas Thank you very much.. That makes all sense.

**Comment by JonatanSalas** [comment]
You are welcome! We are doing our best! :smile:

**Comment by danigomez** [comment]
Hello!, I just published the first version of redux-autoform-bootstrap-ui and redux-autoform-utils!, 
I moved the localizers, helpers and ComponentFactory to utils(After properly tested we should remove those files from redux-autoform and use the ones that are in redux-autoform-utils module). 
Now those can be used in core and any other UI to create new implementations. :smile:

**Comment by JonatanSalas** [comment]
I'm developing in redux-autoform a branch that makes the code to work with your npm packages @danigomez, if I finish it then I will try to merge with master the changes..

**Comment by JonatanSalas** [comment]
I come here again to talk about the advance we have so you know it. This are the tasks that we have completed: 
- [x] Make the library as a core and UI agnostic. 
- [x] Make small git repositories for differents UI types components and expose an index.js api. 
- [x] Make a git project as boilerplate for those collaborators who want to add it's own ui types. 
- [x] Fix codecov and coveralls to view % of test coverage 
- [x] Fix travis-ci and greenkeeper
- [x] Re define the way to declare the schema to make it more easier to read, and make a util class to treat as an array.
- [X] Add support for file-upload components.
- [X] Define how styles per ui type project should be managed. Modular CSS? Inline styles with the help of radium lib? 

This are the pending tasks: 
- [ ] Create a homepage and update the documentation and make one demo per ui git project. 
- [ ] Add support for Wizard/Questionnaire Style form. 
- [ ] Migrate redux-form from v5.X to v6.X when released and full tested. 
- [ ] Improve testing. 
- [ ] Support for Asynchronous validation. 
- [ ] Support for readOnly metadata. 
- [ ] Make a generic Context 

This is a really big progress, we are making this rock guys!

**Comment by JonatanSalas** [comment]
Since we have the other issues active I will close this one. Because the biggest changes that we want to make in AutoForm just finished.
