### ISSUE TITLE
Select items should be able to be generated from a url

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#41]
We could add url metadata option to the select field, and the responsability for the select to fetch it's own resources. 
This will be good in cases where you need to generate the select from data in a web service

**Comment by andrerpena** [comment]
We should do 2 things:
1. Make the `options` metadata compatible with 2 types: Array (As it is today) and a function that returns a Promise. This way we allow it to load data asynchronously.
2. Create a `url` metadata from which the Select should get the options.

**Bonus quest**:
Interdependent Selects is a pretty common use case. Example: You got a Select for **Province** and a Select for **City**. The City only displays cities of the given province.

The obvious solution for the above problem is this:

``` javascript
    url: (m) => `/api/cities/${m.province}`
```

... but we could think of providing an alternative non-function alternative like:

``` javascript
    url: "/api/cities/:province" 
```

I'm not sure about the latest but that's an option.

**Comment by suchostone** [comment]
Hi! are you planning to deliver this feature soon? thanks!

**Comment by suchostone** [comment]
Will Lookup component include this feature as well? Thanks.

**Comment by JonatanSalas** [comment]
@suchostone, I need to define some things with @andrerpena and then I will start to work on this.

**Comment by JonatanSalas** [comment]
We are now working on this redux-autoform/redux-autoform-bootstrap-ui#15

**Comment by JonatanSalas** [comment]
I will close this issue since it's related to the UI project. Follow the referenced issue!
