### ISSUE TITLE
Update codecov and coverrals support

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#42]
I have to edit karma.config.js file from all git repositories to add support for coverrals and codecov.

**Comment by andrerpena** [comment]
Do we need cupport for both coveralls and codecov? The only reason why I added codecov is because I couldn't make coveralls to work. Anyways.. none have worked :stuck_out_tongue_winking_eye:

**Comment by JonatanSalas** [comment]
@andrerpena well, I'm looking how to make it work, coveralls or codecov needs to get the data from the karma execution. In our case, this is not resolved yet, so because of this, we can't see yet the coveralls/codecov results. 

I have looked for this two projects: 

https://github.com/caitp/karma-coveralls
https://github.com/kt3k/codecov-karma-example

Taking a look at both of them and putting hands on work we would solve this! Let me know which one would you like to have only :)

**Comment by andrerpena** [comment]
I think I tried adding the karma script but it apparently continued not working... Hope you'll find the problem :smile:

**Comment by JonatanSalas** [comment]
I will do my best to get this working! :smile:

**Comment by JonatanSalas** [comment]
@andrerpena I have added it but it throws an error with status code 400 from codecov when finished the travis-ci build :/ 

I have to invest more time on this.

**Comment by andrerpena** [comment]
god damn it.. thanks for your effort Jonatan.. Really.

**Comment by JonatanSalas** [comment]
well, I will waste it for now, but some time later I will come back to make this work.

**Comment by JonatanSalas** [comment]
@andrerpena I finally discover how to add this! Working on it now! I have added codecov for redux-autoform-bootstrap-ui, I will add coverrals too! :)

**Comment by andrerpena** [comment]
Congratulations. Great. Please just add both if they are both necessary.
The only reason I added codecov was that I couldn't make coveralls to work.
You pick.

Em 24 de jul de 2016 11:56 AM, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
Yes, I will add both! :)

**Comment by JonatanSalas** [comment]
@andrerpena this is almost done too.

**Comment by andrerpena** [comment]
Perfect job!

**Comment by JonatanSalas** [comment]
Took a time, but it's a great tool for us! :)
