### ISSUE TITLE
arbitrarily nested entity support

### ISSUE THREAD

**Issue by tmc** [redux-autoform/redux-autoform#43]
Would supporting nested and repeated entities be considered in-scope for this project?

**Comment by andrerpena** [comment]
@tmc , what exactly do you mean by **nested** and **repeated** entities? 

RAF supports one entity to be used inside the other, and they can be perfectly leveraged and used multiple times, see the default example in the demo: https://redux-autoform.github.io/redux-autoform/demo.html

What exactly is your use-case? I'll be glad to help.

**Comment by tmc** [comment]
I overlooked that. Can the nesting be arbitrarily deep? For example, could you pull email type into it's own entity and have the email entity reference it?

**Comment by andrerpena** [comment]
Yes you can :)

**Comment by tmc** [comment]
great!
