### ISSUE TITLE
Remove underscore and clone libs and refactor code using native ES6 functions.

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#46]
The following files are using functions provided by underscore and clone which can be replaced by native ES6 code.
- metadata\evaluator\filter\arrayMetadataFilter.js
- metadata\evaluator\filter\defaultMetadataFilter.js
- metadata\evaluator\filter\entityMetadataFilter.js
- metadata\evaluator\metadataEvaluator.js
- metadata\model\modelParser.js
- metadata\validator\metadataValidator.js
- metadata\MetadataProvider.js

What do you think??, is there a reason to not change unsderscore to native ES6??

**Comment by andrerpena** [comment]
I don't oppose to it, I just don't find it a priority. Feel free to do it :smile:

**Comment by JonatanSalas** [comment]
@andrerpena with this we reduce some dependencies, we use native es6 syntax and we could make the code for metadata management even more clear to read and understand.

**Comment by danigomez** [comment]
Great! i will start to do this!
