### ISSUE TITLE
Add tests for Metadata code.

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#49]
Hello @andrerpena , in task #46   i'm using the demo to check my changes, but it will be awesome if we can have tests for this code in order to make sure that we are not breaking anything! :smile:

**Comment by JonatanSalas** [comment]
Yes, this will be good because if we want to make some refactor or any addition to the code of the core, we don't break nothing, and we get a better coverage too.

**Comment by JonatanSalas** [comment]
@andrerpena what's your opinion about this?

**Comment by andrerpena** [comment]
I believe we currently only have tests for 
- metadata\validator\metadataValidator.js
- metadata\MetadataProvider.js

I agree we should cover the rest. I'll take it.

**Comment by JonatanSalas** [comment]
@andrerpena thank you very much!

**Comment by JonatanSalas** [comment]
Since there is another issue for test coverage open, I think closing this one.
