### ISSUE TITLE
Define the context for metadata functions

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#5]

**Comment by danigomez** [comment]
Hello @andrerpena, what is this task about?? :stuck_out_tongue:

**Comment by andrerpena** [comment]
So, I changed the title so it's more meaningful.

Here's the thing: Every metadata in RAF can be define both as a literal and a function. This function receives 2 parameters. The first one is the model. The second one is the context. The context is our opportunity to expose everything we think the developer will need.

Possible examples of helpers in the context (to be discussed):
- Number and date localizers.. So it's possible to convert the string representation of a float into an actual number (Redux Forms stores the string, not the number, so you cannot make math operations).
- Possible a way for the user to request services.. Like a "fetch" service so he can make URL calls. Or access the Redux state, or something like this.

This needs to be discussed further.

**Comment by JonatanSalas** [comment]
In the repo of v1, metadata is provided via React Context-API, and each component access things through a Component with a render-prop.
