### ISSUE TITLE
Solve PhantomJS issue with MetadataProvider test

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#55]
When merge @danigomez refactor, we now that it was a trouble with MetadataProvider test when running with Karma on PhantomJS. It seems to be a trouble of phantomJS, needs a little bit of investigation.

**Comment by andrerpena** [comment]
Can you link to the problem? What is that?

**Comment by JonatanSalas** [comment]
@andrerpena The current build of the travis-ci is failing due to the phantomJS test, when running it with karma throws a:
`
         undefined is not a function/constructor`

Here is the log on travis-ci: 

https://travis-ci.org/redux-autoform/redux-autoform/builds/147575071

**Comment by andrerpena** [comment]
So.. it seems that `find` is not a function. This is the result of the attempt to remove underscore.

**Comment by andrerpena** [comment]
I'll take a look at it now

**Comment by danigomez** [comment]
It's not a problem with find, it seems to be a PhantomJS issue, the tests works correctly using the Chrome browser option in Karma, or running them directly with Mocha.....

**Comment by JonatanSalas** [comment]
@andrerpena find is a function and exists because on chrome we can execute the test without a trouble, and chrome is a native browser, PhantomJS emulates the internal browser apis, so it could exist the posibility of a bad emulation that causes this issue.

**Comment by andrerpena** [comment]
I see.. At least it's possible to reproduce locally using phantom

![image](https://cloud.githubusercontent.com/assets/1581429/17159714/c3bb2b2c-5375-11e6-88d7-6dc25494972c.png)

**Comment by JonatanSalas** [comment]
Yes, that's the error :confused: we will try to investigate a bit about this and try solve it.

**Comment by andrerpena** [comment]
Find is undefined specifically in this case:

![image](https://cloud.githubusercontent.com/assets/1581429/17159914/70a8cd0c-5377-11e6-9702-6b3123f1f51d.png)

This logs this:

![image](https://cloud.githubusercontent.com/assets/1581429/17159928/83aaf2d6-5377-11e6-9a62-9dd4a4702c98.png)

**Comment by JonatanSalas** [comment]
okey.. this is because find is for arrays and it should iterate over fields.. okey :/

**Comment by JonatanSalas** [comment]
Okey, excuse what I say before.

**Comment by danigomez** [comment]
But, it is an array as i can see in the log....

**Comment by andrerpena** [comment]
For some reason **this** array doesn't have find...

**Comment by JonatanSalas** [comment]
Jaja bad mine, I looked fastly! :/

**Comment by danigomez** [comment]
There is a polyfill in the PhantomJS for the find function.... https://github.com/ariya/phantomjs/issues/14054 , maybe that solves the issue!

**Comment by andrerpena** [comment]
@danigomez great. Can you test then? Thank you.

**Comment by andrerpena** [comment]
As a side note, @danigomez , I've seen you refactored all the methods to be _static_, which makes sense.. but does it makes sense to use **this** inside static methods? I mean.. I come from C# and this is like heresy. I know it works.. but **this** is for instance types. Wouldn't you agree?

**Comment by JonatanSalas** [comment]
@andrerpena using the keyword "this" to reference a static method in ES6 is needed because, after all, a javascript class is a prototype at low level.. that is the reason that you need to use this.

**Comment by JonatanSalas** [comment]
@andrerpena we come from java world and this is a little bit creepy... but sadly this is the way :/

**Comment by andrerpena** [comment]
ok.. if that's how the world is today.. :disappointed: :smile: :smile:

**Comment by danigomez** [comment]
Our eyes bleeded when we found out that we must bind all the methods to his class in the constructor in ES6 xD

**Comment by JonatanSalas** [comment]
Seems strange for us... but we don't have to forget that javascript is prototype oriented, so It may vary a little bit much more than our precious c++ like languages jajaja

**Comment by JonatanSalas** [comment]
@danigomez but then we found that class properties + arrow functions solved this dirty part of method binding jaja xD

**Comment by danigomez** [comment]
Fixed! :smile:

**Comment by andrerpena** [comment]
Great!
