### ISSUE TITLE
Proposal for a new direction for this organization

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#58]
So, RAF is an interesting project but it's just one component of the project I envision. What I envision is a platform for creating data-centric business applications, like a CRM or a full-fledged ERP.

Three components that I can think about right now are:
- RAF (For building forms dynamically)
- Dashboard (For draggable widgets). React-grid-layout may be of use: https://github.com/STRML/react-grid-layout
- Admin panel (For the overall application outline, this would contain the notification bar at the top, the login/user dropdown and the main manu at the left). Example: https://github.com/akveo/blur-admin

I'm willing to go all the way on creating these components... If you @JonatanSalas and @danigomez would like to help I'd appreciate very much. For that reason, if you want to contribute, I'd like to rename this organization to something more generic and make it encompass these components I mentioned.

Besides, as I talked to @JonatanSalas already, I'm really liking MaterialUI. It seems really solid, so I wouldn't mind creating the Dashboard and the Admin panel using Material.

What do you think?

**Comment by JonatanSalas** [comment]
@andrerpena I really agree with that, and I think that @danigomez would not have any trouble too. So, If you want to, let's rename the organization. :smile:

**Comment by danigomez** [comment]
i totally agree with the idea!, Go for it!

**Comment by andrerpena** [comment]
I'm glad to know you're in :smile:. Let's think of a good name for the organization now.

**Comment by JonatanSalas** [comment]
@andrerpena that's always a big problem jajajaj get a good name. Well, I will think and let you know!

**Comment by andrerpena** [comment]
Unfortunately I'm going through so much lately that I'm not even thinking about expanding this organization for now. I mean.. I'll continue to maintain RAF, definitely, but I unfortunately I can't bring in more projects right now. If you really want to do this, please reopen.

I appreciate your willingness to help.
