### ISSUE TITLE
Pre loaded Radio Buttons aren't being shown "checked"

### ISSUE THREAD

**Issue by juanih** [redux-autoform/redux-autoform#60]
Hi Team, first of all congratulations for your work, the project is awesome.

I was trying to use forms with radio buttons and I have a problem to load initial values for them. Actually, the values are charged successfully, because they are sent into the form after submit, but the problem is in the browser. The radio buttons with initials values aren't being shown "cheked".

I try to use the following initial values in the demo project, included in the repository:

{
   'default': 'option1',
   'required': 'option3',
   'addonBefore': 'option2',
   'addonAfter': 'option1',
   'help': 'option2'
}

but the referenced Radio Buttons aren't checked in the view. Seems that the property checked="true" is not being used in the component. Or maybe I´m doing something wrong.

Thanks for your help!
Juan.

**Comment by andrerpena** [comment]
Thanks for reporting. I'll take a look at it.

**Comment by andrerpena** [comment]
I'm still involved with publishing and testing the Redux-Form props that were missing. If @JonatanSalas or @danigomez can take a look, that'd be great. Otherwise I'll looking into it right after.

**Comment by andrerpena** [comment]
I think this commit should have fixed it: https://github.com/redux-autoform/redux-autoform-bootstrap-ui/commit/7b91acc69d3f909a9f6aeaaa944db9709286ef56

I already bumped the version but I could not publish because I don't have permission. @danigomez , can you please give me permission on npmjs? Thanks.

**Comment by danigomez** [comment]
@andrerpena i was about to check this issue, but you already solved it! jajaja, cool!. Now you should be able to publish!

**Comment by andrerpena** [comment]
@danigomez I was able to publish it now. Thank you. Yes.. I think I solved it (works on the local demo). If it doesn't work @juanih can reopen it.

**Comment by juanih** [comment]
Thanks @andrerpena and @danigomez. You're working quickly!! I'll take a look and I reopen the issue if something doesn't work. Thanks!
