### ISSUE TITLE
Creating a "Wizard Context" using the redux-form state values

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#69]
Hi @andrerpena !!, We were trying to figure out how to get the form values from the Wizard in order to pass that values to the transition function, that will handle the steps transitions in case that you want to make it conditional. So we come to the idea to simply connect the group to the redux store and read the "form" (We can assume that the reducer is combined with that value, because that's what the RF doc says! :smile: ) state value. 
Does it make sense to connect a group to the store?? or it should be handled in a parent component and passed to the group?? 
What do you think??

**Comment by andrerpena** [comment]
Hey @danigomez . I'm sorry, I didn't understand your question. Probably because I'm not 100% aligned with the way you're implementing this.

Why do you have to connect each group individually to the store? I mean... Doesn't it make sense that the entire wizard is **one form** from RF's perspective? I'm just saying. The advantage is that if one property **repeats** throughout the form, the values will automatically be filled.

Are'nt I getting something?

If you think it's too difficult to talk here we can schedule a Skype call right away. Thanks.

**Comment by danigomez** [comment]
mmmm, maybe i wasn't clear enough with my question :stuck_out_tongue: . I have the following situation, let's say that i have the following schema and a layout using the WizardGroup:
``` javascript
{
    entities: [
        {
            name: "contact",
            fields: [
                { name: "f1", displayName: "Field 1", type: "string" },
                { name: "f2", displayName: "Field 2", type: "string" },
                { name: "f3", displayName: "Field 3", type: "string" },
                { name: "f4", displayName: "Field 4", type: "string" },
                { name: "f5", displayName: "Field 5", type: "string" }
            ],
            layouts: [
                {
                    name: 'edit',
                    component: 'WizardGroup',
                    groups: [
                        {
                            title: 'First',
                            fields: [
                                {
                                    name: 'f1'
                                },
                                {
                                    name: 'f2',
                                    size: 8
                                }
                            ],
                            transition: (context) => {
                                        if(context.f1 === "Hello!") 
                                              context.goToStep(3);  
                                       else 
                                            context.next();
                            }
                        },
			{
                            title: 'Second',
                            fields: [
                                {
                                    name: 'f2'
                                },
                                {
                                    name: 'f3',
                                    size: 8
                                }
                            ]
                        },
			{
                            title: 'Third',
                            fields: [
                                {
                                    name: 'f4'
                                },
                                {
                                    name: 'f5',
                                    size: 8
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```
In order to allow the user to evaluate a condition and after that jump to a specific step, i need some way to expose the field values that are currently loaded in the form, that way the user can evaluate using any field filled previosly. The problem is, how do i obtain those values??, one of my thoughts was to connect this group to the RF state, so that way i can access that values through the `context `param passed to the `transition `function that the user define for any step that requires it.

**Comment by danigomez** [comment]
Forget about this.... those values are automatically passed by RF..... :confused:

**Comment by andrerpena** [comment]
I just came here to answer you. Good you found the answer already. Whatever that is :smile:

**Comment by danigomez** [comment]
I neede the fields of the RF... and then i realized as @JonatanSalas  pointed that those value are in....... (suspense music)..... the fields prop xD

**Comment by andrerpena** [comment]
huaha that was funny
