### ISSUE TITLE
Support text-expressions

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#71]
Ok, as @JonatanSalas mentioned. JSON doesn't support functions. Lints will complain and so forth. 

We need to support text-expressions. I'm going to do it. This thread is just for discussion.

**Comment by JonatanSalas** [comment]
Actually the possible workaround to use functions is to have the Schema stored in JS file. I mention this as a remember me. 

Things that we have to deal with: 
- special characters on strings
- define a way to help the metadata processor to recognize normal text vs text expressions

I think that's all..

**Comment by andrerpena** [comment]
So, I have the code to do it already. Because it happens to be supported in React-Metaform, which is also mine: https://github.com/gearz-lab/react-metaform

You got the point right! How do we know if a string is an expression?

on React-Metaform, this is how I did this:

```
{
    required: "_exp:m.value > 3000";
}
```

The `_exp` prefix indicates a text expression.

**If you don't like it**, we can prefix the metadata itself. JS allows two non-[a-z] characters to start a string: _ and $. RAF uses $ already to denote a lazy function. That is, a function that shouldn't be evaluated, but rather passed to the component. We're left with _. So... You pick.

**Comment by andrerpena** [comment]
I can solve this one fairly easily. I just didn't finish this one today because I got the password problem to solve which I did.

**Comment by danigomez** [comment]
Hey @andrerpena !! So using the $ i can pass a function to a component???, i'm having troubles passing functions to the WizardGroup, it's wierd that in the demo is working but no in the project i'm doing.... :/

**Comment by JonatanSalas** [comment]
@andrerpena how are you going with this? Do you need some help?

**Comment by andrerpena** [comment]
In metadata properties starting with $ functions are not supposed to be
evaluated so yes.. You are supposed to be able to pass functions to your
components

Em 22 de ago de 2016 23:42, "Daniel Gómez" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
Ok, this is good! So this issue can be closed?

**Comment by andrerpena** [comment]
If there's not a confirmed bug then yes, this should be closed. I didn't test it again though

**Comment by JonatanSalas** [comment]
Ok, I will close it! If we have a trouble we will reopen it
