### ISSUE TITLE
Why is this on experimental state now?

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform#77]
@danigomez and @JonatanSalas , what exactly is the feature that keeps this version in experimental state, just out of curiosity?

**Comment by danigomez** [comment]
The changes on AutoformInternal for the Root component, autoform-utils is also in experimental for the same reason and bootstrap-ui for the Wizard, but if you're okay with those changes we can just release in latest!! :smile:

**Comment by andrerpena** [comment]
Ah ok. The form itself seems to be in an ok state. I still didn't have the time to look into the Wizard :disappointed:  I'm sorry. If you're not that confident yet, we should keep that in experimental :smile: Thank you.
