### ISSUE TITLE
Add refs in every field created in ComponentFactory.

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform#82]
Hi @andrerpena, @JonatanSalas !, In order to handle the focus in a field in case of error i was thinking to add a `ref="<field_name">` when the field is created in the Factory, if i'm not mistaken doing this we can handle`this.refs.<field_name>.focus()` inside the Group, because each field will be a children in the group, what do you think????

**Comment by JonatanSalas** [comment]
@andrerpena since you are working in the redux-form v6 solution could you consider to use the Field component prop withRef and set a ref that points to the name of the field?

**Comment by andrerpena** [comment]
I'll take this into account on the RF6 refactoring

**Comment by JonatanSalas** [comment]
Thank you!

**Comment by JonatanSalas** [comment]
With v1 repo this has first class support.
