### ISSUE TITLE
ButtonToolbar should receive more props than submitting?

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform#83]
I have been thinking about this, ButtonToolbar actually just receives the prop submitting. Would be good if ButtonToolbar receives too the pristine value as prop and the errors object as prop?

I'm asking this, because it would be good to block the submit button on those case when you have errors that aren't validated with the current Validators that redux-autoform core provides, this would acts as work around till we add more validators! 

@andrerpena @danigomez What's your opinion?

**Comment by JonatanSalas** [comment]
I will add support to this, as a workaround and launch an experimental tag version to use it. Then when you can, we can discuss a better solution :smile:

**Comment by andrerpena** [comment]
I think that it makes sense that button bar receives something that informs it whether or not there has been any errors.

**Comment by JonatanSalas** [comment]
@andrerpena @danigomez Well, this is currently supported now. I have publish an experimental tag version to use it and test in other UI libraries! :smile:

**Comment by JonatanSalas** [comment]
Reopen because of a bug I have introduced when iterating the fields to get the errors. The current code work in all case except when you use and ArrayContainer. I'm working to fix this issue and updating the demo to add the ArrayContainer and test it's behaviour.

**Comment by JonatanSalas** [comment]
done!
