### ISSUE TITLE
onBlur is not a function with FieldGroups

### ISSUE THREAD

**Issue by devang-kredx** [redux-autoform/redux-autoform#87]
Am getting the following error when using autoform with groups using bootstrap EditComponentFactory.

```
FormControl.js?6d41:52 Uncaught TypeError: onBlur is not a function
FormControl._this.handleBlur @ FormControl.js?6d41:52
```

The following is the schema I am using-

```
const schema =
{
    entities: [
        {
            name: "repaymentAmount",
            fields: [
                // Amount Pending
                {
                    name: "amount_pending.total",
                    displayName: "Total",
                    type: "float"
                },
                {
                    name: "amount_pending.paid",
                    displayName: "Paid",
                    type: "float"
                },
                {
                    name: "amount_pending.writeoff",
                    displayName: "Writeoff",
                    type: "float"
                },

                // Remarks
                {
                    name: "remarks",
                    displayName: "Remarks",
                    type: "string"
                },
            ],
            layouts: [
                {
                    name: "edit",
                    fields: [
                        {
                            name: "amountPending",
                            displayName: "Amount Pending",
                            type: "group",
                            group: "gAmountPending"
                        },
                        {
                            name: "remarks",
                            displayName: "Remarks",
                        }
                    ],
                    groups: [
                        {
                            name: "gAmountPending",
                            fields: [
                              {
                                name: "amount_pending.total",
                                size: 4,
                              },
                              {
                                name: "amount_pending.paid",
                                size: 4,
                              },
                              {
                                name: "amount_pending.writeoff",
                                size: 4,
                              },
                            ]
                        },
                    ]
                }
            ]
        }
    ]
}
```

**Comment by JonatanSalas** [comment]
The problem is around Group or FieldGroup? They are different components. Which version of Redux Autoform Bootstrap are you using?

**Comment by devang-kredx** [comment]
@JonatanSalas I am using the following- `"redux-autoform-bootstrap-ui": "^1.6.0",`

How to distinguish between groups and field groups. I am using the schema (as provided above) inspired from this [demo](https://redux-autoform.github.io/redux-autoform-bootstrap-ui/demo.html?preset=componentsFieldGroup) and the autoform usages as-

```
    render() {
      const autoFormProps = {
        form: 'repaymentForm',
        schema: schema,
        componentFactory: EditComponentFactory,
        entityName: 'repaymentAmount',
        buttonBar: () => <div></div>,
        fieldLayout: "123",
        layoutName: "edit",
        initialValues: {},
        onSubmit: (...args) => console.log(args),
      };
      return (
          <div>
            <AutoForm {...autoFormProps} />
          </div>
      );
    }
```

**Comment by JonatanSalas** [comment]
Seems to be a bug in the latest version. Try testing in the demo your schema. It should work. 

We are working a lot on this, so maybe it could be some troubles. Later I will check it out. If you want you can use instead of the release package, the package we use to test the latest features. 

Do the following in console:

``` bash
npm view redux-autofom
npm view redux-autofom-bootstrap-ui
```

And take the latest one with **-experimental** 

Another thing, the property fieldLayout value should be "stacked"/"inline". I don't know if this could introduce the trouble you got, but change it and test again too..

**Comment by devang-kredx** [comment]
Hmm.... the schema works on the demo. But using the latest -experimental version or 1.0.1 of redux-autoform-bootstrap-ui continues to give the same error.

**Comment by andrerpena** [comment]
@devang-kredx , thanks for the report.

The problem has nothing to do with FieldGroup. FieldGroup is a `type`/`component` so you can display a group occupying the space of a field.

I don't know what this error is. I'll investigate, but one thing is for sure. `amount_pending.total` is not a valid identifier for a field. We should probably have some sort of validation.

I'll investigate and let you know.

**Comment by devang-kredx** [comment]
@andrerpena The problem was indeed due to dot notation. Removing the dot notation from field names fixed this issue.

**Comment by andrerpena** [comment]
Ok good. Thank you
