### ISSUE TITLE
Bug in Float Value

### ISSUE THREAD

**Issue by devang-kredx** [redux-autoform/redux-autoform#91]
Putting a 0 value gives "Invalid decimal"
https://redux-autoform.github.io/redux-autoform-bootstrap-ui/demo.html?preset=componentsTextBoxFloat

**Comment by JonatanSalas** [comment]
I will take a look at it! Thank you!

**Comment by andrerpena** [comment]
Thanks for reporting

**Comment by devang-kredx** [comment]
@JonatanSalas Checking in to see if there is any estimate by when this bug would be resolved?

**Comment by JonatanSalas** [comment]
I will take a look this weekend. Because this week I'm with a lot of work :/

**Comment by devang-kredx** [comment]
Just FYI, the issue is that the following code is being triggered with 0 float value. Not sure why.
https://github.com/redux-autoform/redux-autoform-utils/blob/master/src/localization/numbroLocalizer.js#L18

**Comment by andrerpena** [comment]
OMG.. Good catch. Those should be ===.  I didn't analyze it further but
that's what I think at first sight. Can someone send a PR?

Em 21 de set de 2016 10:04 AM, "devang-kredx" notifications@github.com
escreveu:

**Comment by devang-kredx** [comment]
Looks like its already fixed in autoforms-utils. Anything needs to be
changed in react-autoform to pick this fix?

**Comment by andrerpena** [comment]
I ended up fixing the line you pointed out. If this is not the only source of the problem, this is surely one.

We need to publish a new version of the utils, update the redux-autoform reference and republish it. I don't know if I'll be able to do it in a timely manner because I got lots of work. But I'll try as soon as I can.

**Comment by devang-kredx** [comment]
Closed via #96
